name: wdi
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  animate_do: ^4.2.0
  bloc: ^9.1.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: ^1.3.1
  dio: ^5.9.0
  easy_localization: ^3.0.8
  easy_stepper: ^0.9.1
  expandable_page_view: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_blurhash: ^0.9.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.3
  freezed_annotation: ^3.1.0
  get_it: ^9.1.0
  go_router: ^17.0.0
  intl: any
  json_annotation: ^4.9.0
  logger: ^2.6.0
  lottie: ^3.3.2
  photo_view: ^0.15.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.0.1
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.10.4
  flutter_gen_runner: ^5.12.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: null
  retrofit_generator: null

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/lottie/
    - assets/translations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/light.ttf
          weight: 300
        - asset: assets/fonts/regular.ttf
          weight: 400
        - asset: assets/fonts/medium.ttf
          weight: 500
        - asset: assets/fonts/semi_bold.ttf
          weight: 600
        - asset: assets/fonts/bold.ttf
          weight: 700
        - asset: assets/fonts/extra_bold.ttf
          weight: 800
        - asset: assets/fonts/black.ttf
          weight: 900
